User.create!([
  {username: "device", password: "password"},
  {username: "kennyS", password: "password"},
  {username: "Skadoodle", password: "password"},
  {username: "s1mple", password: "password"},
  {username: "flusha", password: "password"},
  {username: "KRiMZ", password: "password"},
  {username: "Snax", password: "password"},
  {username: "Happy", password: "password"},
  {username: "GuardiaN", password: "password"},
  {username: "olofm", password: "password"},

  {username: "Guest", password: "password"}
])

Itemdb.create!([
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png"},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png"},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png"},
  {name: "Howl", price: 500.0, gun_type: "M4A4", condition: "Factory New", rarity: "Contraband", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/howl_uhr4yy.png"},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png"},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png"}
])

Match.create!([
  {has_started: false, map: "de_dust2", current_round: 0}
])
Team.create!([
  {name: "WOW_WE_LAGGED", odds: 1.0, avatar_url: "https://res.cloudinary.com/dqucbuno8/image/upload/h_250,w_250/v1447814571/lag-kills-people_nrbbgr.png"},
  {name: "php_poets", odds: 1.0, avatar_url: "https://res.cloudinary.com/dqucbuno8/image/upload/c_fill,h_250,w_250/v1447827745/dedicated-php-developer_zfcdls.png"}
])
MatchLineup.create!([
  {match_id: 1, team_id: 1},
  {match_id: 1, team_id: 2}
])

Item.create!([
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 1},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 1},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 1},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 1},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 1},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 1},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 1},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 1},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 1},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 1},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 2},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 2},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 2},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 2},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 2},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 2},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 2},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 2},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 2},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 2},
  {name: "Howl", price: 500.0, gun_type: "M4A4", condition: "Factory New", rarity: "Contraband", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/howl_uhr4yy.png", user_id: nil, bet_id: 3},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 3},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 3},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 3},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 3},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 3},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 3},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 3},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 3},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 3},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 4},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 4},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 4},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 4},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 4},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 4},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 4},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 4},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 4},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 4},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 5},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 5},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 5},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 5},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 5},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 5},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 5},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 5},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 5},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 5},
  {name: "Howl", price: 500.0, gun_type: "M4A4", condition: "Factory New", rarity: "Contraband", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/howl_uhr4yy.png", user_id: nil, bet_id: 6},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 6},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 6},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 6},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 6},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 6},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 6},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 6},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 6},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 6},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 7},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 7},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 7},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 7},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 7},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 7},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 7},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 7},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 7},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 7},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 8},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 8},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 8},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 8},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 8},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 8},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 8},
  {name: "Origami", price: 4.0, gun_type: "Sawed-Off", condition: "Minimal Wear", rarity: "Mil-Spec", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/origami_xopke7.png", user_id: nil, bet_id: 8},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 8},
  {name: "Forest DDPAT", price: 0.77, gun_type: "MP7", condition: "Battle-Scarred", rarity: "Consumer Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814186/ddpat_suubqw.png", user_id: nil, bet_id: 8},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 9},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 9},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 9},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 9},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 9},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 9},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 9},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 9},
  {name: "Blue Steel", price: 9.51, gun_type: "Bayonet", condition: "Field-Tested", rarity: "Covert", is_stattrack: false, is_souvenir: true, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/bluesteel_er3oeo.png", user_id: nil, bet_id: 9},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 9},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 10},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 10},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 10},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 10},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 10},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 10},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 10},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 10},
  {name: "Frontside Misty", price: 5.0, gun_type: "AK-47", condition: "Field-Tested", rarity: "Classified", is_stattrack: true, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/frontsidemisty_xfeh8a.png", user_id: nil, bet_id: 10},
  {name: "Mudder", price: 1.23, gun_type: "Desert Eagle", condition: "Well-Worm", rarity: "Industrial Grade", is_stattrack: false, is_souvenir: false, image_url: "https://res.cloudinary.com/dqucbuno8/image/upload/v1447814183/mudder_weljxg.png", user_id: nil, bet_id: 10}
])

Bet.create!([
  {user_id: 1, match_id: 1, team_id: 1, total_value: 66.6},
  {user_id: 2, match_id: 1, team_id: 1, total_value: 24.46},
  {user_id: 3, match_id: 1, team_id: 1, total_value: 537.3},
  {user_id: 4, match_id: 1, team_id: 2, total_value: 40.48},
  {user_id: 5, match_id: 1, team_id: 2, total_value: 41.02},
  {user_id: 6, match_id: 1, team_id: 2, total_value: 533.25},
  {user_id: 7, match_id: 1, team_id: 1, total_value: 40.56},
  {user_id: 8, match_id: 1, team_id: 2, total_value: 28.05},
  {user_id: 9, match_id: 1, team_id: 1, total_value: 86.82},
  {user_id: 10, match_id: 1, team_id: 1, total_value: 46.23}
])
